javalinThreeVersion: 3.13.13
javalinversion: 5.3.1
slf4jversion: 2.0.3
repourl: https://github.com/javalin/javalin.github.io
description: Javalin - A lightweight Java and Kotlin web framework. Create REST APIs in Java or Kotlin easily.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
